BINS=main.elf 

# put here the additional .o files you want to generate
# one .c file for each .o should be present
OBJS=./src/uart.o
OBJS+=./src/timer_interrupt.o

# put here the additional header files needed for compilation
HEADERS=./src/uart.h


# the file below contains the actual rules

# !!!!!!!!!!!!!!!! MODIFY HERE !!!!!!!!!!!!!!!! 

include ./src/avr.mk