BINS=main
# put here the additional .o files you want to generate
# one .c file for each .o should be present
OBJS=./src/serial.o
OBJS+=./src/plot.o
OBJS+=./src/utils.o
OBJS+=main.o  # Aggiungi questa linea per includere main.c

# put here the additional header files needed for compilation
HEADERS=./src/serial.h
HEADERS+=./src/plot.h
HEADERS+=./src/utils.h

# the file below contains the actual rules
include ./src/linux.mk